NER_Zeroshot = 'Please list all entity words in the text that fit the category.Output format is "word1: type1; word2: type2". \nOption: [product_food, other_award, person_director, art_painting, person_actor, person_politician, building_theater, location_mountain, product_car, person_athlete, other_educationaldegree, person_soldier, product_weapon, location_island, location_other, other_law, art_broadcastprogram, product_other, art_music, building_library, product_game, person_other, building_hotel, other_currency, art_other, organization_education, event_other, product_train, person_scholar, organization_government/governmentagency, organization_politicalparty, product_airplane, art_writtenart, organization_media/newspaper, event_attack/battle/war/militaryconflict, event_election, building_airport, organization_showorganization, location_road/railway/highway/transit, product_software, organization_other, product_ship, location_bodiesofwater, other_biologything, building_hospital, event_protest, organization_sportsleague, other_livingthing, location_park, other_god, building_sportsfacility, location_GPE, other_medical, other_language, building_restaurant, other_astronomything, person_artist/author, other_chemicalthing, other_disease, organization_religion, organization_company, art_film, organization_sportsteam, event_disaster, building_other, event_sportsevent]\n\n'


RC_Zeroshot = 'Please classify relationships between the two entities (marked with <entity> and </entity>). The output format is "(word1; relation1; word2); (word3; relation2; word3);". \nOption: [Container and Content, Whole and Component, Topic and Message, Message and Topic, Instrument and Agency, Member and Collection, Content and Container, Entity and Origin, Origin and Entity, Effect and Cause, Entity and Destination, Destination and Entity, Producer and Product, Product and Producer, Collection and Member, Component and Whole, Cause and Effect, Agency and Instrument].\n\n'


ED_Zeroshot = 'Please tell me event type and its trigger word from given type options. Output format is "trigger: type". \nOption: [elect, endposition, injure, startposition, mergeorg, artifact, meet, marry, endorg, transfermoney, demonstrate, transportperson, die, divorce, releaseparole, extradite, broadcast, transportartifact, pardon, startorg, arrestjail, sentence, declarebankruptcy, convict, appeal, transferownership, beborn, fine, nominate, transaction, acquit, chargeindict, execute, trialhearing, attack, sue, correspondence, contact]\n\n'

EAE_Zeroshot = 'Given event type and trigger, please tell me the arguments of all the listed option. Output format is "name1: role1; name2: role2"\nOption: {options}\n\n'

ERE_Zeroshot = 'Please classify relationships between the two entities (marked with <entity> and </entity>). The output format is "(word1; relation1; word2); (word3; relation2; word3);". \nOption: [before, after, vague, none, equal]\n\n'
