DESC = {
    "Component-Whole(e2,e1)": "A larger whole encompasses an object as one of its components.",
    "Instrument-Agency(e2,e1)": "An agent uses an instrument.",
    "Member-Collection(e1,e2)": "A member forms a nonfunctional part of a collection.",
    "Cause-Effect(e2,e1)": "An effect is brought about by an event or object.",
    "Entity-Destination(e1,e2)": "An entity is moving towards a destination.",
    "Content-Container(e1,e2)": "An object (Content) is physically stored in a delineated area of space (Container).",
    "Message-Topic(e1,e2)": "A message, written or spoken, is about a topic.",
    "Product-Producer(e2,e1)": "A producer causes a product to exist.",
    "Member-Collection(e2,e1)": "A nonfunctional part of a collection is constituted by a member.",
    "Entity-Origin(e1,e2)": "An entity is coming or is derived from an origin (e.g., position or material).",
    "Cause-Effect(e1,e2)": "An event or object leads to an effect.",
    "Component-Whole(e1,e2)": "An object is a component of a larger whole.",
    "Message-Topic(e2,e1)": "A topic is the subject of a written or spoken message.",
    "Product-Producer(e1,e2)": "Product is a product of Producer",
    "Entity-Origin(e2,e1)": "An origin (e.g., position or material) is where an entity comes from or is derived.",
    "Content-Container(e2,e1)": "A delineated area of space (Container) physically contains an object (Content).",
    "Instrument-Agency(e1,e2)": "An instrument is the instrument (tool) of an agent.",
    "Entity-Destination(e2,e1)": "A destination is being approached by an entity.",
}
